import { customAlphabet } from "nanoid";

/**
 * Prefixed primary keys, generated by the app.
 *
 * These used to come from Postgres via `@default(dbgenerated("'drf_' || …"))`,
 * but D1 is SQLite and has no gen_random_uuid(). Generating them here is
 * strictly better for this app anyway: D1 has no interactive transactions, so
 * knowing every id before the first write is what lets the create-draft route
 * commit the draft, its teams and its picks in a single atomic D1 batch
 * (src/app/api/drafts/route.ts).
 *
 * nanoid draws from crypto.getRandomValues, which is native in workerd. The
 * alphabet is lowercase alphanumeric so ids stay copy-pasteable and
 * case-insensitively unique; 24 chars is ~124 bits of entropy.
 */
const nano = customAlphabet("0123456789abcdefghijklmnopqrstuvwxyz", 24);

export type IdPrefix =
  | "drf"
  | "tm"
  | "pck"
  | "fb"
  // Punishment wheel: the wheel, one of its options, and an entry in the
  // public ideas database.
  | "pun"
  | "pop"
  | "pid";

export function newId(prefix: IdPrefix): string {
  return `${prefix}_${nano()}`;
}
