import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import { BrandMark } from "@/components/brand-mark";
import { Wordmark } from "@/components/wordmark";
import { buildMetadata } from "@/lib/seo/metadata";
import { BreadcrumbLd } from "@/lib/seo/jsonld";
import { NewDraftForm } from "./new-draft-form";
import { toEntrySource } from "@/lib/db-enums";
import type { ImportSource } from "@/lib/importers/types";

const IMPORT_SOURCES: ImportSource[] = [
  "SLEEPER",
  "MFL",
  "FLEAFLICKER",
  "ESPN",
];

function parseSource(value: string | string[] | undefined) {
  if (typeof value !== "string") return undefined;
  const upper = value.toUpperCase();
  return IMPORT_SOURCES.find((s) => s === upper);
}

// ?tab=manual | ?tab=import — anything else (including no param) falls back to import.
function parseTab(value: string | string[] | undefined) {
  if (typeof value !== "string") return undefined;
  const lower = value.toLowerCase();
  return lower === "manual" || lower === "import" ? lower : undefined;
}

// Slugs are generated by src/lib/slug.ts and are always lowercase words joined
// by hyphens. Anything else is somebody editing the URL, so drop it rather
// than sending it to the API to be looked up.
function parseSlug(value: string | string[] | undefined) {
  if (typeof value !== "string") return undefined;
  const trimmed = value.trim().toLowerCase();
  return /^[a-z0-9-]{1,64}$/.test(trimmed) ? trimmed : undefined;
}

export const metadata = buildMetadata({
  title: "Schedule a Fantasy Football Draft Order",
  description:
    "Set up a fair, transparent fantasy football draft order in under a minute. Pick a time, add your teams or import your league, and share one link. The randomizer fires live for the whole league.",
  path: "/new",
  keywords: [
    "schedule fantasy draft order",
    "create fantasy draft order",
    "fantasy draft order randomizer",
    "fantasy football draft order generator",
    "draft order picker",
    "draft order lottery",
  ],
});

export default async function NewDraftPage({
  searchParams,
}: {
  searchParams: Promise<Record<string, string | string[] | undefined>>;
}) {
  const params = await searchParams;
  const initialSource = parseSource(params.source);
  const rawLeagueId = params.leagueId;
  const initialLeagueId =
    typeof rawLeagueId === "string" ? rawLeagueId.trim() : undefined;
  const initialMode = parseTab(params.tab);
  // Viral plumbing: ?from= is the draft that sent this person here, ?src= is
  // which link on it they clicked, ?clone= copies an existing draft's teams.
  // All three are optional and all three are validated on the server before
  // they reach the database (src/app/api/drafts/route.ts).
  const referrerSlug = parseSlug(params.from);
  const entrySource = toEntrySource(
    typeof params.src === "string" ? params.src : undefined,
  );
  const cloneSlug = parseSlug(params.clone);

  return (
    <div className="flex min-h-full flex-col">
      <BreadcrumbLd
        items={[
          { name: "Home", path: "/" },
          { name: "Schedule a draft", path: "/new" },
        ]}
      />
      <header className="border-sideline/50 bg-midnight/90 border-b backdrop-blur-md">
        <div className="mx-auto flex h-16 max-w-3xl items-center justify-between px-4 sm:px-6">
          <Link href="/" className="flex items-center gap-2.5">
            <BrandMark />
            <Wordmark />
          </Link>
        </div>
      </header>
      <main className="relative flex-1">
        <div className="pointer-events-none absolute inset-0 overflow-hidden">
          <div className="bg-signal/5 absolute top-0 left-1/2 h-[400px] w-[700px] -translate-x-1/2 rounded-full blur-[120px]" />
        </div>
        <div className="relative mx-auto w-full max-w-2xl px-4 py-12 sm:px-6 sm:py-16">
          <Link
            href="/"
            className="text-hashmark hover:text-chalk mb-6 inline-flex items-center gap-1.5 text-sm transition-colors"
          >
            <ArrowLeft className="size-4" />
            Back
          </Link>
          <div className="mb-8">
            <p className="text-signal font-mono text-xs font-medium tracking-wider uppercase">
              New draw
            </p>
            <h1 className="font-display text-chalk mt-2 text-4xl font-bold tracking-tight sm:text-5xl">
              Set up your draw.
            </h1>
            <p className="text-hashmark mt-3">
              A free fantasy football draft order generator: pick a time, and
              the randomizer draws your league&apos;s order live on a spinner
              everyone watches together. Once scheduled, your draft cannot be
              edited. Share the link with your league.
            </p>
          </div>
          <NewDraftForm
            initialMode={initialMode}
            initialSource={initialSource}
            initialLeagueId={initialLeagueId}
            referrerSlug={referrerSlug}
            entrySource={entrySource}
            cloneSlug={cloneSlug}
          />
        </div>
      </main>
    </div>
  );
}
