// Worker entrypoint (wrangler `main`). Wraps the OpenNext-generated handler.
//
// This app has no background work by design — the randomized order and every
// pick's revealedAt are written in the create-draft request, and passage of
// time is the only trigger — so there is no queue() or scheduled() handler
// here. Just fetch, plus the Durable Object re-exports OpenNext's cache layer
// needs wrangler to resolve.

// @ts-expect-error generated by `opennextjs-cloudflare build`
import { default as handler } from "./.open-next/worker.js";
import { injectGoogleAnalytics } from "./worker-analytics";
// Live viewer count on /d/[slug]. Ephemeral in-memory state, no storage, no
// bearing on the draw itself — see the file header for why it is not in D1.
import { DraftPresence } from "./worker/draft-presence";

// Vulnerability scanners constantly probe for these paths (.env, .php,
// wp-admin, .git, backup files). None of them exist here, so short-circuit
// before OpenNext's routing does any work. This is a second line of defense;
// the primary block is a Cloudflare WAF Custom Rule at the edge, declared by
// the Pulumi program in program/, which rejects the request before it counts
// as a Worker invocation at all.
const SCANNER_PATH_PATTERN =
  /\.(?:env(?:\.\w+)?|php\d?|bak|sql|git|aws|log|swp|zip|tar|gz|ini|yml|yaml)(?:$|\?)|\/(?:wp-admin|wp-login\.php|wp-includes|xmlrpc\.php|\.git|\.env|\.aws|phpmyadmin|admin\.php|config\.php)(?:$|\/)/i;

const worker = {
  async fetch(request: Request, env: CloudflareEnv, ctx: ExecutionContext) {
    const url = new URL(request.url);
    // Canonical host: NEXT_PUBLIC_BASE_URL has no www, so 301 www -> apex,
    // preserving path and query. Both hostnames are attached to this worker as
    // Custom Domains.
    if (url.hostname === "www.fantasyfootballdraftorder.com") {
      url.hostname = "fantasyfootballdraftorder.com";
      return Response.redirect(url.toString(), 301);
    }
    if (SCANNER_PATH_PATTERN.test(url.pathname + url.search)) {
      return new Response("Not found", { status: 404 });
    }
    const response = await handler.fetch(request, env, ctx);
    // GA4 tag appended to <head> on HTML responses. No-op when the var is
    // unset. See worker-analytics.ts for why this is not a CF Snippet.
    return injectGoogleAnalytics(
      request,
      response,
      (env as Record<string, unknown>).GA_MEASUREMENT_ID as string | undefined,
    );
  },
};

export default worker;

// Durable Objects used by OpenNext's cache layer must be re-exported from the
// entrypoint even when unused, so wrangler can resolve the classes.
// @ts-expect-error generated by `opennextjs-cloudflare build`
export { DOQueueHandler, DOShardedTagCache } from "./.open-next/worker.js";

// Unlike the two above, this one is actually bound (DRAFT_PRESENCE in
// wrangler.jsonc), so it also carries a migrations entry there.
export { DraftPresence };
