import type { PrismaConfig } from "prisma";
import { localD1Url } from "./scripts/local-d1.mjs";

/**
 * Prisma CLI config.
 *
 * The app never uses this datasource url — at runtime the database is the
 * Cloudflare D1 binding (src/lib/prisma.ts). It exists purely so the CLI has
 * something to open: Prisma Studio and `migrate diff` point at the same local
 * SQLite file that miniflare and `wrangler d1 migrations apply --local` use.
 *
 * Migrations are generated by `pnpm db:migrate:new` (prisma migrate diff) and
 * applied by wrangler; Prisma Migrate does not drive D1.
 */
export default {
  schema: "prisma/schema",
  migrations: {
    path: "prisma/migrations",
    seed: "pnpm exec tsx prisma/seed.ts",
  },
  datasource: {
    url: localD1Url(),
  },
} satisfies PrismaConfig;
