-- CreateTable
CREATE TABLE "Punishment" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "slug" TEXT NOT NULL,
    "leagueName" TEXT NOT NULL,
    "loserName" TEXT NOT NULL,
    "creatorName" TEXT NOT NULL,
    "creatorEmail" TEXT,
    "scheduledFor" DATETIME NOT NULL,
    "revealedAt" DATETIME NOT NULL,
    "chosenPosition" INTEGER NOT NULL,
    "seed" TEXT NOT NULL,
    "commitSha" TEXT,
    "entrySource" TEXT NOT NULL DEFAULT 'DIRECT',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "PunishmentOption" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "punishmentId" TEXT NOT NULL,
    "label" TEXT NOT NULL,
    "position" INTEGER NOT NULL,
    CONSTRAINT "PunishmentOption_punishmentId_fkey" FOREIGN KEY ("punishmentId") REFERENCES "Punishment" ("id") ON DELETE CASCADE ON UPDATE CASCADE
);

-- CreateTable
CREATE TABLE "PunishmentIdea" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "label" TEXT NOT NULL,
    "category" TEXT NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'PENDING',
    "email" TEXT,
    "userAgent" TEXT,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "approvedAt" DATETIME
);

-- CreateIndex
CREATE UNIQUE INDEX "Punishment_slug_key" ON "Punishment"("slug");

-- CreateIndex
CREATE INDEX "Punishment_scheduledFor_idx" ON "Punishment"("scheduledFor");

-- CreateIndex
CREATE INDEX "PunishmentOption_punishmentId_idx" ON "PunishmentOption"("punishmentId");

-- CreateIndex
CREATE UNIQUE INDEX "PunishmentOption_punishmentId_position_key" ON "PunishmentOption"("punishmentId", "position");

-- CreateIndex
CREATE INDEX "PunishmentIdea_status_category_idx" ON "PunishmentIdea"("status", "category");

-- CreateIndex
CREATE INDEX "PunishmentIdea_createdAt_idx" ON "PunishmentIdea"("createdAt");

-- Seed the ideas database.
--
-- Everything above this line is generated by `pnpm db:migrate:new`; everything
-- below is hand-written. Seed data in a schema migration is unusual, but it is
-- what makes /fantasy-football-punishments ship with the deploy instead of
-- needing a separate remote load, and it keeps local, preview and production
-- starting from the same list.
--
-- Ids are hand-written and stable rather than generated, because they travel in
-- `/punishment/new?ideas=<id>,<id>` links. Changing one breaks every shortlist
-- anyone has shared. Add new curated ideas in a LATER migration; never edit
-- these rows here, since applied migrations are never re-run.
--
-- Timestamps are RFC3339 with an explicit +00:00 and milliseconds, which is how
-- Prisma represents DateTime on SQLite. NOT CURRENT_TIMESTAMP: that yields
-- "YYYY-MM-DD HH:MM:SS", which Prisma cannot read back. A fixed literal also
-- keeps this migration byte-reproducible for the deploy workflow's drift check.
INSERT INTO "PunishmentIdea" ("id", "label", "category", "status", "createdAt", "approvedAt") VALUES
  ('pid_seed_waffle_house',   'Waffle House marathon: one hour for every point you lost by',        'FOOD',      'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_gas_station',    'Every meal from a gas station for three days',                        'FOOD',      'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_raw_onion',      'Eat a raw onion like an apple, filmed',                               'FOOD',      'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_ghost_pepper',   'Ghost pepper wing challenge: one wing per league member',             'FOOD',      'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_one_restaurant', 'One fast food restaurant, every single meal, for a week',             'FOOD',      'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_mystery_drink',  'Drink a smoothie blended from one ingredient chosen by each owner',   'FOOD',      'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),

  ('pid_seed_rival_jersey',   'Wear the jersey of your most hated rival for a full game day',        'WARDROBE',  'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_mascot_suit',    'Wear a full mascot costume to the next draft',                        'WARDROBE',  'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_sandwich_board', 'Wear a Last Place sandwich board at a shopping mall for an hour',     'WARDROBE',  'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_tutu',           'Wear a tutu everywhere you go for an entire weekend',                 'WARDROBE',  'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_hot_dog',        'Be a hot dog for Halloween. No negotiation',                          'WARDROBE',  'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_beach_suit',     'Full suit and tie at the beach for an entire day',                    'WARDROBE',  'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),

  ('pid_seed_senior_photos',  'Sit for cheesy senior portraits, framed copy to every owner',         'PUBLIC',    'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_street_corner',  'One hour on a busy corner holding a Last Place sign',                 'PUBLIC',    'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_anthem',         'Sing the national anthem at a local rec league game',                 'PUBLIC',    'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_open_mic',       'Five minutes of stand-up at an open mic, all about your season',      'PUBLIC',    'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_water_boy',      'Serve as water boy and runner on next season draft night',            'PUBLIC',    'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_read_lineups',   'Read your five worst lineup decisions aloud at the next draft',       'PUBLIC',    'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_host_draft',     'Plan, pay for, and host the entire draft party next season',          'PUBLIC',    'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),

  ('pid_seed_milk_mile',      'The milk mile: run a mile, drink a gallon of milk, keep it down',     'ENDURANCE', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_yard_tent',      'Sleep in a tent in your own front yard for one full night',           'ENDURANCE', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_5k_pads',        'Complete a 5K in full football pads',                                 'ENDURANCE', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_worst_movie',    'Watch the worst-reviewed movie in theaters, alone, start to finish',  'ENDURANCE', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_4am_week',       'Wake up at 4am every day for a week and text the league proof',       'ENDURANCE', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_polar_plunge',   'Polar plunge into the coldest water within driving distance, filmed', 'ENDURANCE', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),

  ('pid_seed_bio_rewrite',    'The league writes your social media bio and it stays up a month',     'DIGITAL',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_profile_pic',    'The league picks your profile picture until next season starts',      'DIGITAL',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_praise_video',   'Post a two-minute video praising the champion by name',               'DIGITAL',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_one_post',       'The league gets to send exactly one post from your account',          'DIGITAL',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_ringtone',       'League-chosen ringtone for a month, and you may not silence it',      'DIGITAL',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_wallpaper',      'The champion is your phone wallpaper until the next draft',           'DIGITAL',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),

  ('pid_seed_donation',       'Donate to a charity the champion picks',                              'CHARITY',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_food_bank',      'Volunteer a full shift at a food bank, photo required',               'CHARITY',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_buy_dinner',     'Buy the entire league dinner on draft night next season',             'CHARITY',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_pay_dues',       'Pay the champion league dues for next season',                        'CHARITY',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_shelter_animal', 'Sponsor a shelter animal and name it after the champion',             'CHARITY',   'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),

  ('pid_seed_league_tattoo',  'Tattoo chosen by the league, no bigger than a quarter',               'PERMANENT', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_temp_tattoo',    'Temporary tattoo of the league logo, reapplied daily for a month',    'PERMANENT', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_shame_trophy',   'Buy the last-place trophy, engrave your name, display it all year',   'PERMANENT', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_hall_of_shame',  'Permanent entry in the league hall of shame, read aloud every year',  'PERMANENT', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_framed_start',   'Your worst start-sit of the season, framed, hung at every draft',     'PERMANENT', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00'),
  ('pid_seed_team_name',      'The champion chooses your team name for all of next season',          'PERMANENT', 'APPROVED', '2026-07-25T00:00:00.000+00:00', '2026-07-25T00:00:00.000+00:00');
